/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_53c2e113 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/kkmybbvhinqfhglbkzbj/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => {
  const url = Deno.env.get("SUPABASE_URL");
  const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  
  if (!url || !key) {
    throw new Error(`Missing Supabase credentials: URL=${!!url}, KEY=${!!key}`);
  }
  
  return createClient(url, key);
};

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_53c2e113").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_53c2e113").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_53c2e113").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_53c2e113").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_53c2e113").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_53c2e113").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_53c2e113").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Search for key-value pairs by prefix with pagination support.
export const getByPrefixPaginated = async (
  prefix: string,
  page: number = 1,
  pageSize: number = 100,
  searchTerm?: string
): Promise<{ data: any[], total: number, page: number, pageSize: number, totalPages: number }> => {
  const supabase = client();
  
  // First, get all matching records by prefix
  const { data: allData, error: fetchError } = await supabase
    .from("kv_store_53c2e113")
    .select("key, value")
    .like("key", prefix + "%")
    .order('key', { ascending: true });
  
  if (fetchError) {
    throw new Error(fetchError.message);
  }
  
  let filteredData = allData?.map((d) => d.value) ?? [];
  
  // Apply search filter if provided (case-insensitive search on name field)
  if (searchTerm && searchTerm.trim()) {
    const lowerSearch = searchTerm.toLowerCase().trim();
    filteredData = filteredData.filter((item: any) => {
      return item?.name?.toLowerCase().includes(lowerSearch);
    });
  }
  
  // Calculate pagination
  const total = filteredData.length;
  const totalPages = Math.ceil(total / pageSize);
  
  // Get the slice for the current page
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  const paginatedData = filteredData.slice(start, end);
  
  return {
    data: paginatedData,
    total,
    page,
    pageSize,
    totalPages
  };
};